<script lang="ts" setup>
import { ref, computed, onMounted, onUnmounted } from 'vue';
import {
  ListRules, AddRule, UpdateRule, DeleteRule, Interfaces,
  Groups, ApplyGroup, DeleteGroupRules, SetGroupEnabled,
  ListProxies, ListXray, BulkUpdateRules, RuleExitIP,
} from '../../wailsjs/go/main/App';
import type { ipc } from '../../wailsjs/go/models';
import GroupIcon from './GroupIcon.vue';

// Local shape for a proxy row — same fields as ipc.ProxyDTO; using a
// local type means the component still type-checks while wailsjs/models
// is being regenerated by Wails on the next dev/build.
type ProxyRow = {
  id: number;
  name: string;
  protocol: string;
  host: string;
  port: number;
  username: string;
  hasPassword: boolean;
  createdAt: string;
  updatedAt: string;
};

// Local mirror of XrayDTO — see above for the rationale.
type XrayRow = {
  id: number;
  name: string;
  outbound: string;
  socksPort: number;
  enabled: boolean;
  createdAt: string;
  updatedAt: string;
};

const emit = defineEmits<{ (e: 'changed'): void }>();

const rules = ref<ipc.RuleDTO[]>([]);
const interfaces = ref<ipc.InterfaceDTO[]>([]);
const proxies = ref<ProxyRow[]>([]);
const xrays = ref<XrayRow[]>([]);
const knownGroups = ref<ipc.GroupDTO[]>([]);
const error = ref<string>('');
const pendingDelete = ref<number | null>(null);
const pendingDeleteGroup = ref<string | null>(null);
const search = ref<string>('');
// Per-rule exit-IP probe results, keyed by rule id. Fetched
// automatically after rules load (bounded concurrency) and re-fetchable
// per row via the retry button. The daemon caches each probe for a few
// minutes, so the auto-fetch and any retries stay cheap.
const exitInfo = ref<Record<number, ipc.ExitIPResult>>({});
const exitLoading = ref<Record<number, boolean>>({});
// Which rows have their exit IP revealed (default: masked).
const revealedExitIPs = ref<Record<number, boolean>>({});
let pendingDeleteTimer: number | undefined;
let pendingDeleteGroupTimer: number | undefined;
let ifaceTimer: number | undefined;

function normalizePattern(p: string): string {
  return p.toLowerCase().trim().replace(/\.$/, '');
}

const sleep = (ms: number) => new Promise(r => setTimeout(r, ms));

// Turn a 2-letter ISO country code into its flag emoji.
function flagEmoji(cc?: string): string {
  if (!cc || cc.length !== 2) return '';
  const base = 0x1f1e6;
  const up = cc.toUpperCase();
  return String.fromCodePoint(base + up.charCodeAt(0) - 65, base + up.charCodeAt(1) - 65);
}

// maskIP hides the host-specific part of an IP address.
// IPv4: keeps first two octets → 104.16.*.*   IPv6: keeps first group.
function maskIP(ip: string): string {
  if (!ip) return '';
  if (ip.includes(':')) return ip.split(':')[0] + ':…';
  const p = ip.split('.');
  return p.length === 4 ? `${p[0]}.${p[1]}.*.*` : ip;
}

function toggleExitReveal(id: number) {
  revealedExitIPs.value = { ...revealedExitIPs.value, [id]: !revealedExitIPs.value[id] };
}

// Probe (or re-probe) the public exit IP a rule's matched traffic
// egresses through. Result/failure both land in exitInfo so the row can
// render the IP inline or explain why it couldn't be determined.
async function checkExitIP(r: ipc.RuleDTO) {
  exitLoading.value[r.id] = true;
  try {
    exitInfo.value[r.id] = await RuleExitIP(r.id);
  } catch (e: any) {
    exitInfo.value[r.id] = {
      interface: r.interface, exitIp: '', country: '', region: '', city: '',
      probed: false, message: e?.message || String(e),
    } as ipc.ExitIPResult;
  } finally {
    exitLoading.value[r.id] = false;
  }
}

// Auto-fetch exit IPs for every non-block rule that doesn't already have
// a result, with a small concurrency cap so the daemon isn't slammed and
// rows fill in progressively. Called after each rules refresh; rules
// already probed (or in flight) are skipped, so it's cheap to re-run.
const EXIT_IP_CONCURRENCY = 4;
async function autoFetchExitIPs() {
  const pending = rules.value.filter(
    r => r.action !== 'block' && !exitInfo.value[r.id] && !exitLoading.value[r.id],
  );
  if (pending.length === 0) return;
  let i = 0;
  const worker = async () => {
    while (i < pending.length) await checkExitIP(pending[i++]);
  };
  await Promise.all(Array.from({ length: Math.min(EXIT_IP_CONCURRENCY, pending.length) }, worker));
}

// A rule "belongs to" a group when its pattern sits inside the scope
// of any of the group's curated patterns. Mirrors the daemon's
// ruleCoveredByGroupPattern (and the engine's actual wildcard match):
//   group "*.openai.com" covers  openai.com, *.openai.com, api.openai.com, *.api.openai.com
//   group "openai.com"   covers  only the exact "openai.com"
// So a hand-typed rule like "chatgpt.com" lands in OpenAI because
// OpenAI's group lists "*.chatgpt.com".
function ruleCoveredBy(rulePat: string, groupPat: string): boolean {
  const rp = normalizePattern(rulePat);
  const gp = normalizePattern(groupPat);
  if (!rp || !gp) return false;
  if (rp === gp) return true;
  if (!gp.startsWith('*.')) return false;
  const suffix = gp.slice(2);
  const body = rp.startsWith('*.') ? rp.slice(2) : rp;
  return body === suffix || body.endsWith('.' + suffix);
}

function groupForRule(r: ipc.RuleDTO): ipc.GroupDTO | undefined {
  for (const g of knownGroups.value) {
    for (const p of g.patterns) {
      if (ruleCoveredBy(r.pattern, p)) return g;
    }
  }
  return undefined;
}

// "Lazy" group match: a query hits a group if it's a substring of the
// key, display name, description, or any pattern. Same matcher is used
// for the quick-add cards and to surface a group's rules in the list.
function matchesGroup(g: ipc.GroupDTO, q: string): boolean {
  if (!q) return true;
  if (g.key.toLowerCase().includes(q)) return true;
  if (g.displayName.toLowerCase().includes(q)) return true;
  if (g.description.toLowerCase().includes(q)) return true;
  return g.patterns.some(p => p.toLowerCase().includes(q));
}

const filteredGroups = computed<ipc.GroupDTO[]>(() => {
  const q = search.value.trim().toLowerCase();
  if (!q) return knownGroups.value;
  return knownGroups.value.filter(g => matchesGroup(g, q));
});

const filteredRules = computed<ipc.RuleDTO[]>(() => {
  const q = search.value.trim().toLowerCase();
  if (!q) return rules.value;
  return rules.value.filter(r => {
    if (r.pattern.toLowerCase().includes(q)) return true;
    const g = groupForRule(r);
    return g ? matchesGroup(g, q) : false;
  });
});

// Sectioned view: an array of {group | null, rules[]}, in display
// order. Groups come first (in the registry's order), then an
// "Ungrouped" bucket. Empty sections (after search filter) are
// dropped so the user sees only what matches.
type Section = { group: ipc.GroupDTO | null; rules: ipc.RuleDTO[] };

const sections = computed<Section[]>(() => {
  const byGroup = new Map<string, ipc.RuleDTO[]>();
  const ungrouped: ipc.RuleDTO[] = [];
  for (const r of filteredRules.value) {
    const g = groupForRule(r);
    if (g) {
      const list = byGroup.get(g.key) ?? [];
      list.push(r);
      byGroup.set(g.key, list);
    } else {
      ungrouped.push(r);
    }
  }
  const out: Section[] = [];
  for (const g of knownGroups.value) {
    const list = byGroup.get(g.key);
    if (list && list.length) out.push({ group: g, rules: list });
  }
  if (ungrouped.length) out.push({ group: null, rules: ungrouped });
  return out;
});

// Bulk-state for a group: 'on' if every rule enabled, 'off' if every
// disabled, 'mixed' otherwise. Drives the section-header toggle.
function groupEnabledState(rs: ipc.RuleDTO[]): 'on' | 'off' | 'mixed' {
  if (!rs.length) return 'off';
  const onCount = rs.filter(r => r.enabled).length;
  if (onCount === rs.length) return 'on';
  if (onCount === 0) return 'off';
  return 'mixed';
}

async function setGroupEnabledAll(g: ipc.GroupDTO, enabled: boolean) {
  try {
    await SetGroupEnabled(g.key, enabled);
    await refresh();
    emit('changed');
  } catch (e: any) {
    error.value = e?.message || String(e);
  }
}

// Collapse/expand state per section. Group sections start collapsed
// to keep the list scannable; the ungrouped bucket (the user's own
// rules) starts expanded. Applying a group expands its section so the
// freshly created rules are visible. User toggles persist for the
// lifetime of the component (no localStorage — nothing to migrate).
const expanded = ref<Set<string>>(new Set(['__ungrouped__']));
function sectionKey(g: ipc.GroupDTO | null): string {
  return g ? g.key : '__ungrouped__';
}
function isCollapsed(g: ipc.GroupDTO | null): boolean {
  return !expanded.value.has(sectionKey(g));
}
function toggleCollapse(g: ipc.GroupDTO | null) {
  const k = sectionKey(g);
  const next = new Set(expanded.value);
  if (next.has(k)) next.delete(k); else next.add(k);
  expanded.value = next;
}
function expandSection(key: string) {
  if (expanded.value.has(key)) return;
  const next = new Set(expanded.value);
  next.add(key);
  expanded.value = next;
}

function askDeleteGroup(g: ipc.GroupDTO) {
  if (pendingDeleteGroup.value === g.key) {
    confirmDeleteGroup(g);
    return;
  }
  pendingDeleteGroup.value = g.key;
  if (pendingDeleteGroupTimer) window.clearTimeout(pendingDeleteGroupTimer);
  pendingDeleteGroupTimer = window.setTimeout(() => {
    pendingDeleteGroup.value = null;
  }, 3000);
}

async function confirmDeleteGroup(g: ipc.GroupDTO) {
  if (pendingDeleteGroupTimer) window.clearTimeout(pendingDeleteGroupTimer);
  pendingDeleteGroup.value = null;
  try {
    await DeleteGroupRules(g.key);
    await refresh();
    emit('changed');
  } catch (e: any) {
    error.value = e.toString();
  }
}

// Group-apply working state. When the user clicks a group card, this
// gets populated with the same shape as `draft` so the same binding
// picker UI can be reused.
const groupApply = ref<{
  key: string;
  action: 'block' | 'route';
  binding: 'iface' | 'proxy' | 'xray';
  iface: string;
  proxies: string[];
  xrays: string[];
  enabled: boolean;
} | null>(null);

function openGroupForm(g: ipc.GroupDTO) {
  groupApply.value = {
    key: g.key,
    action: 'block',
    binding: 'iface',
    iface: '',
    proxies: [],
    xrays: [],
    enabled: true,
  };
}

function closeGroupForm() { groupApply.value = null; }

function toggleGroupProxy(name: string) {
  if (!groupApply.value) return;
  const idx = groupApply.value.proxies.indexOf(name);
  if (idx >= 0) groupApply.value.proxies.splice(idx, 1);
  else groupApply.value.proxies.push(name);
}

function toggleGroupXray(name: string) {
  if (!groupApply.value) return;
  const idx = groupApply.value.xrays.indexOf(name);
  if (idx >= 0) groupApply.value.xrays.splice(idx, 1);
  else groupApply.value.xrays.push(name);
}

function groupInterfaceField(): string {
  const g = groupApply.value;
  if (!g || g.action !== 'route') return '';
  if (g.binding === 'proxy' && g.proxies.length > 0) return `proxy:${g.proxies.join(',')}`;
  if (g.binding === 'xray' && g.xrays.length > 0) return `xray:${g.xrays.join(',')}`;
  if (g.binding === 'iface') return g.iface;
  return '';
}

function groupApplyValid(): boolean {
  const g = groupApply.value;
  if (!g) return false;
  if (g.action === 'block') return true;
  if (g.binding === 'iface') return !!g.iface;
  if (g.binding === 'proxy') return g.proxies.length > 0;
  if (g.binding === 'xray') return g.xrays.length > 0;
  return false;
}

async function applyGroup() {
  const g = groupApply.value;
  if (!g || !groupApplyValid()) return;
  try {
    const result = await ApplyGroup(g.key, g.action, groupInterfaceField(), g.enabled);
    const created = result.created?.length || 0;
    const skipped = result.skipped?.length || 0;
    error.value = '';
    if (skipped > 0) {
      error.value = `Created ${created} rule(s); ${skipped} pattern(s) skipped (already exist).`;
    }
    groupApply.value = null;
    expandSection(g.key);
    await refresh();
    emit('changed');
  } catch (e: any) {
    error.value = e?.message || String(e);
  }
}

function groupByKey(key: string): ipc.GroupDTO | undefined {
  return knownGroups.value.find(g => g.key === key);
}

// Action model:
//   block — return NXDOMAIN
//   route — let through and pin the resolved IPs to a binding
//
// allow exists in the daemon for "explicit pass-through that
// overrides a broader block" but is not exposed in the UI — the
// implicit default for unmatched domains is already "allow".
const draft = ref({
  pattern: '',
  action: 'block' as 'block' | 'route',
  // Only meaningful when action === 'route':
  binding: 'iface' as 'iface' | 'proxy' | 'xray',
  iface: '',
  proxies: [] as string[],
  xrays: [] as string[],
  enabled: true,
});

function draftInterfaceField(): string {
  if (draft.value.action !== 'route') return '';
  if (draft.value.binding === 'proxy' && draft.value.proxies.length > 0) {
    return `proxy:${draft.value.proxies.join(',')}`;
  }
  if (draft.value.binding === 'xray' && draft.value.xrays.length > 0) {
    return `xray:${draft.value.xrays.join(',')}`;
  }
  if (draft.value.binding === 'iface') return draft.value.iface;
  return '';
}

function draftIsValid(): boolean {
  if (!draft.value.pattern.trim()) return false;
  if (draft.value.action === 'block') return true;
  // route requires a non-empty binding
  if (draft.value.binding === 'iface') return !!draft.value.iface;
  if (draft.value.binding === 'proxy') return draft.value.proxies.length > 0;
  if (draft.value.binding === 'xray') return draft.value.xrays.length > 0;
  return false;
}

function toggleDraftProxy(name: string) {
  const idx = draft.value.proxies.indexOf(name);
  if (idx >= 0) {
    draft.value.proxies.splice(idx, 1);
  } else {
    draft.value.proxies.push(name);
  }
}

function toggleDraftXray(name: string) {
  const idx = draft.value.xrays.indexOf(name);
  if (idx >= 0) draft.value.xrays.splice(idx, 1);
  else draft.value.xrays.push(name);
}

// ---- Bulk selection + retarget ---------------------------------------
//
// The bulk toolbar lets the user retarget many rules to a new
// (action, interface) pair in one IPC round-trip. Selection is a Set of
// rule IDs so toggling stays O(1) regardless of how many rules are
// loaded. We deliberately preserve selection across `refresh()` —
// stale IDs are tolerated by the daemon (it skips not-found entries).
//
// "Select all visible" respects the search filter so the user can
// type e.g. `xray:old-name` into the search, hit Select all, and
// retarget the whole filtered set to a new xray entry in one step.

const selected = ref<Set<number>>(new Set());

function isSelected(id: number): boolean {
  return selected.value.has(id);
}

function toggleSelected(id: number) {
  const next = new Set(selected.value);
  if (next.has(id)) next.delete(id); else next.add(id);
  selected.value = next;
}

function clearSelection() {
  selected.value = new Set();
}

function selectAllVisible() {
  const next = new Set<number>();
  for (const r of filteredRules.value) next.add(r.id);
  selected.value = next;
}

const selectedCount = computed<number>(() => selected.value.size);

function sectionSelectionState(rs: ipc.RuleDTO[]): 'all' | 'some' | 'none' {
  if (!rs.length) return 'none';
  let on = 0;
  for (const r of rs) if (selected.value.has(r.id)) on++;
  if (on === 0) return 'none';
  if (on === rs.length) return 'all';
  return 'some';
}

function toggleSection(rs: ipc.RuleDTO[]) {
  const next = new Set(selected.value);
  const state = sectionSelectionState(rs);
  if (state === 'all') {
    for (const r of rs) next.delete(r.id);
  } else {
    for (const r of rs) next.add(r.id);
  }
  selected.value = next;
}

// Editor panel state, mirroring `draft` minus pattern/enabled.
type BulkState = {
  action: 'block' | 'route';
  binding: 'iface' | 'proxy' | 'xray';
  iface: string;
  proxies: string[];
  xrays: string[];
};
const bulk = ref<BulkState | null>(null);

function openBulk() {
  bulk.value = {
    action: 'block',
    binding: 'iface',
    iface: '',
    proxies: [],
    xrays: [],
  };
}

function closeBulk() { bulk.value = null; }

function toggleBulkProxy(name: string) {
  if (!bulk.value) return;
  const idx = bulk.value.proxies.indexOf(name);
  if (idx >= 0) bulk.value.proxies.splice(idx, 1);
  else bulk.value.proxies.push(name);
}

function toggleBulkXray(name: string) {
  if (!bulk.value) return;
  const idx = bulk.value.xrays.indexOf(name);
  if (idx >= 0) bulk.value.xrays.splice(idx, 1);
  else bulk.value.xrays.push(name);
}

function bulkInterfaceField(): string {
  const b = bulk.value;
  if (!b || b.action !== 'route') return '';
  if (b.binding === 'proxy' && b.proxies.length > 0) return `proxy:${b.proxies.join(',')}`;
  if (b.binding === 'xray' && b.xrays.length > 0) return `xray:${b.xrays.join(',')}`;
  if (b.binding === 'iface') return b.iface;
  return '';
}

function bulkIsValid(): boolean {
  const b = bulk.value;
  if (!b) return false;
  if (b.action === 'block') return true;
  if (b.binding === 'iface') return !!b.iface;
  if (b.binding === 'proxy') return b.proxies.length > 0;
  if (b.binding === 'xray') return b.xrays.length > 0;
  return false;
}

async function applyBulk() {
  const b = bulk.value;
  if (!b || !bulkIsValid() || selected.value.size === 0) return;
  try {
    const ids = [...selected.value];
    const result = await BulkUpdateRules(ids, b.action, bulkInterfaceField());
    const affected = result?.affected ?? 0;
    error.value = '';
    if (affected < ids.length) {
      error.value = `Updated ${affected} of ${ids.length} rule(s); the rest were missing.`;
    }
    selected.value = new Set();
    bulk.value = null;
    await refresh();
    emit('changed');
  } catch (e: any) {
    error.value = e?.message || String(e);
  }
}

// ---- Inline edit ------------------------------------------------------

type EditState = {
  id: number;
  pattern: string;
  action: 'block' | 'route';
  binding: 'iface' | 'proxy' | 'xray';
  iface: string;
  proxies: string[];
  xrays: string[];
  enabled: boolean;
};

const editing = ref<EditState | null>(null);

function beginEdit(r: ipc.RuleDTO) {
  let binding: 'iface' | 'proxy' | 'xray' = 'iface';
  let iface = '';
  let proxyNames: string[] = [];
  let xrayNames: string[] = [];
  if (r.interface.startsWith('app:')) {
    // Legacy app-bound rules are being removed daemon-side; degrade
    // gracefully to an empty interface binding so editing doesn't crash.
    binding = 'iface';
    iface = '';
  } else if (r.interface.startsWith('proxy:')) {
    binding = 'proxy';
    proxyNames = r.interface.substring(6).split(',').map(s => s.trim()).filter(Boolean);
  } else if (r.interface.startsWith('xray:')) {
    binding = 'xray';
    xrayNames = r.interface.substring(5).split(',').map(s => s.trim()).filter(Boolean);
  } else if (r.interface) {
    binding = 'iface';
    iface = r.interface;
  }
  // Legacy `allow` rows (pre-action-model split) collapse to `route`
  // when they had an interface, otherwise to `block` for editing.
  const action: 'block' | 'route' = r.action === 'route' ? 'route'
    : (r.action === 'allow' && r.interface) ? 'route'
    : (r.action === 'block') ? 'block'
    : 'block';
  editing.value = {
    id: r.id,
    pattern: r.pattern,
    action,
    binding,
    iface,
    proxies: proxyNames,
    xrays: xrayNames,
    enabled: r.enabled,
  };
}

function cancelEdit() { editing.value = null; }

function editingInterfaceField(): string {
  const e = editing.value;
  if (!e || e.action !== 'route') return '';
  if (e.binding === 'proxy' && e.proxies.length > 0) return `proxy:${e.proxies.join(',')}`;
  if (e.binding === 'xray' && e.xrays.length > 0) return `xray:${e.xrays.join(',')}`;
  if (e.binding === 'iface') return e.iface;
  return '';
}

function editingIsValid(): boolean {
  const e = editing.value;
  if (!e || !e.pattern.trim()) return false;
  if (e.action === 'block') return true;
  if (e.binding === 'iface') return !!e.iface;
  if (e.binding === 'proxy') return e.proxies.length > 0;
  if (e.binding === 'xray') return e.xrays.length > 0;
  return false;
}

function toggleEditingProxy(name: string) {
  if (!editing.value) return;
  const idx = editing.value.proxies.indexOf(name);
  if (idx >= 0) editing.value.proxies.splice(idx, 1);
  else editing.value.proxies.push(name);
}

function toggleEditingXray(name: string) {
  if (!editing.value) return;
  const idx = editing.value.xrays.indexOf(name);
  if (idx >= 0) editing.value.xrays.splice(idx, 1);
  else editing.value.xrays.push(name);
}

async function saveEdit() {
  const e = editing.value;
  if (!editingIsValid()) return;
  try {
    await UpdateRule(e!.id, e!.pattern.trim(), e!.action, editingInterfaceField(), e!.enabled);
    editing.value = null;
    await refresh();
    emit('changed');
  } catch (err: any) {
    error.value = err?.message || String(err);
  }
}

async function refresh() {
  try {
    rules.value = (await ListRules()) || [];
    interfaces.value = (await Interfaces()) || [];
    proxies.value = ((await ListProxies()) || []) as unknown as ProxyRow[];
    xrays.value = ((await ListXray()) || []) as unknown as XrayRow[];
    if (knownGroups.value.length === 0) {
      knownGroups.value = (await Groups()) || [];
    }
    error.value = '';
    // Drop cached exit IPs for rules that no longer exist or whose
    // binding changed, so stale entries don't linger, then auto-fetch
    // any rule still missing a result. Fire-and-forget — the rows fill
    // in as each probe returns.
    const live = new Map(rules.value.map(r => [r.id, r.interface]));
    for (const idStr of Object.keys(exitInfo.value)) {
      const id = Number(idStr);
      if (!live.has(id) || exitInfo.value[id].interface !== live.get(id)) {
        delete exitInfo.value[id];
        delete revealedExitIPs.value[id];
      }
    }
    autoFetchExitIPs();
  } catch (e: any) {
    error.value = e?.message || String(e);
  }
}

async function add() {
  if (!draftIsValid()) return;
  try {
    await AddRule(draft.value.pattern.trim(), draft.value.action,
      draftInterfaceField(),
      draft.value.enabled);
    draft.value.pattern = '';
    draft.value.iface = '';
    draft.value.proxies = [];
    draft.value.xrays = [];
    await refresh();
    emit('changed');
  } catch (e: any) {
    error.value = e?.message || String(e);
  }
}

async function toggle(r: ipc.RuleDTO) {
  try {
    await UpdateRule(r.id, r.pattern, r.action, r.interface, !r.enabled);
    await refresh();
    emit('changed');
  } catch (e: any) {
    error.value = e?.message || String(e);
  }
}

function askDelete(r: ipc.RuleDTO) {
  if (pendingDelete.value === r.id) {
    confirmDelete(r);
    return;
  }
  pendingDelete.value = r.id;
  if (pendingDeleteTimer) window.clearTimeout(pendingDeleteTimer);
  pendingDeleteTimer = window.setTimeout(() => {
    pendingDelete.value = null;
  }, 3000);
}

async function confirmDelete(r: ipc.RuleDTO) {
  if (pendingDeleteTimer) window.clearTimeout(pendingDeleteTimer);
  pendingDelete.value = null;
  try {
    await DeleteRule(r.id);
    await refresh();
    emit('changed');
  } catch (e: any) {
    error.value = e?.message || String(e);
  }
}


async function refreshLive() {
  // Polled every few seconds: interfaces so chips reflect live
  // "running" state without requiring a rule edit. Rules themselves
  // don't refresh here — they only change on user action.
  try {
    interfaces.value = (await Interfaces()) || [];
  } catch (_) { /* ignore — keep last good */ }
}

function ifaceLabel(i: ipc.InterfaceDTO): string {
  return i.owner ? `${i.name} — ${i.owner}` : i.name;
}

// Rule binding helpers. The `interface` field on a Rule can be:
//   ''            → default route
//   'utunN'       → fixed interface
//   'proxy:NAME'  → routed through an upstream HTTP/SOCKS5 proxy
//   'xray:NAME'   → routed through an embedded xray-core outbound
function ruleIsProxy(field: string): boolean { return field.startsWith('proxy:'); }

// "proxy:work,home" → ["work","home"]
function ruleProxyKeys(field: string): string[] {
  return field.replace(/^proxy:/, '').split(',').map(s => s.trim()).filter(Boolean);
}

function ruleIsXray(field: string): boolean { return field.startsWith('xray:'); }

// "xray:a,b" → ["a","b"]
function ruleXrayNames(field: string): string[] {
  return field.replace(/^xray:/, '').split(',').map(s => s.trim()).filter(Boolean);
}

function xrayByName(name: string): XrayRow | undefined {
  return xrays.value.find(x => x.name === name);
}

function xrayStatusBadge(name: string): string {
  const x = xrayByName(name);
  if (!x) return '?';
  return x.enabled ? 'on' : 'off';
}

function xrayStatusLabel(name: string): string {
  const x = xrayByName(name);
  if (!x) return `${name} — xray entry no longer exists`;
  return x.enabled ? `xray entry "${name}" enabled` : `xray entry "${name}" disabled`;
}

function proxyByName(name: string): ProxyRow | undefined {
  return proxies.value.find(p => p.name === name);
}

// One-word "live state" badge for a proxy reference. Phase A doesn't
// have a real health check, so we just report whether the proxy is
// configured ("ok") or missing from the store ("?"). Phase B will
// replace this with a real reachability check.
function proxyStatusBadge(name: string): string {
  return proxyByName(name) ? 'ok' : '?';
}

function proxyStatusLabel(name: string): string {
  const p = proxyByName(name);
  if (!p) return `${name} — proxy no longer exists`;
  return `${p.protocol}://${p.host}:${p.port}`;
}

// True if a rule's saved binding can't be honoured right now.
function bindingDown(field: string): boolean {
  if (!field) return false;
  if (ruleIsProxy(field)) {
    const names = ruleProxyKeys(field);
    return !names.some(n => !!proxyByName(n));
  }
  if (ruleIsXray(field)) {
    const names = ruleXrayNames(field);
    return !names.some(n => {
      const x = xrayByName(n);
      return !!x && x.enabled;
    });
  }
  return !interfaces.value.some(i => i.name === field);
}


onMounted(() => {
  refresh();
  ifaceTimer = window.setInterval(refreshLive, 2000);
});
onUnmounted(() => { if (ifaceTimer) window.clearInterval(ifaceTimer); });
</script>

<template>
  <div class="panel">
    <h2>Rules</h2>
    <div v-if="error" class="error">{{ error }}</div>

    <!-- Search box up top: drives both the quick-add cards below and
         the rules sections further down. Lazy substring match on group
         name/description/patterns and rule pattern. -->
    <div class="row search-row" style="gap: 8px; margin-bottom: 10px">
      <input v-model="search" type="search"
             placeholder="Search rules and groups (e.g. docker, anthropic, *.openai.com)"
             style="flex: 1" />
      <span class="muted" style="font-size: 11px; min-width: 140px; text-align: right">
        {{ filteredGroups.length }} / {{ knownGroups.length }} groups ·
        {{ filteredRules.length }} / {{ rules.length }} {{ rules.length === 1 ? 'rule' : 'rules' }}
      </span>
    </div>

    <!-- Quick add from a known service group -->
    <div class="groups-bar">
      <div class="muted" style="font-size: 11px; margin-bottom: 8px">
        Quick add — one click creates rules for every domain of a service:
      </div>
      <div class="row" style="gap: 6px; flex-wrap: wrap">
        <button v-for="g in filteredGroups" :key="g.key"
                class="group-card"
                @click="openGroupForm(g)"
                :title="g.description + '\n\n' + g.patterns.join('\n')">
          <GroupIcon :group-key="g.key" :size="20" />
          <span class="group-name">{{ g.displayName }}</span>
          <span class="muted" style="font-size: 10px">{{ g.patterns.length }} domain{{ g.patterns.length === 1 ? '' : 's' }}</span>
        </button>
        <span v-if="search.trim() && !filteredGroups.length" class="muted" style="font-size: 11px; padding: 6px">
          No groups match "<code>{{ search }}</code>".
        </span>
      </div>
    </div>

    <!-- Inline group-apply form, opens when a group card is clicked -->
    <div v-if="groupApply" class="add-form" style="border-left: 3px solid var(--accent)">
      <div class="row" style="gap: 10px; align-items: center; margin-bottom: 8px">
        <GroupIcon :group-key="groupApply.key" :size="22" />
        <strong>{{ groupByKey(groupApply.key)?.displayName }}</strong>
        <span class="muted" style="font-size: 11px">
          {{ groupByKey(groupApply.key)?.patterns.length }} pattern(s):
          <code style="font-size: 11px">{{ groupByKey(groupApply.key)?.patterns.join(', ') }}</code>
        </span>
      </div>
      <div class="row" style="gap: 8px">
        <select v-model="groupApply.action" style="width: 100px">
          <option value="block">block</option>
          <option value="route">route</option>
        </select>
        <label class="toggle">
          <input type="checkbox" v-model="groupApply.enabled" />
          <span class="track"></span>
        </label>
        <button class="primary" @click="applyGroup" :disabled="!groupApplyValid()">Create rules</button>
        <button @click="closeGroupForm">Cancel</button>
      </div>
      <div v-if="groupApply.action === 'route'" class="col" style="gap: 10px; margin-top: 10px">
        <div class="row" style="gap: 8px; align-items: center">
          <span class="muted" style="font-size: 11px; min-width: 60px">via:</span>
          <div class="row" style="gap: 0">
            <button :class="['seg', {active: groupApply.binding === 'iface'}]" @click="groupApply.binding = 'iface'">Interface</button>
            <button :class="['seg', {active: groupApply.binding === 'proxy'}]" @click="groupApply.binding = 'proxy'">Proxy</button>
            <button :class="['seg', {active: groupApply.binding === 'xray'}]" @click="groupApply.binding = 'xray'">Xray</button>
          </div>
          <select v-if="groupApply.binding === 'iface'" v-model="groupApply.iface" style="flex: 1">
            <option value="">— pick interface —</option>
            <option v-for="i in interfaces" :key="i.name" :value="i.name">{{ ifaceLabel(i) }} (mtu {{ i.mtu }})</option>
          </select>
          <span v-else-if="groupApply.binding === 'proxy'" class="muted" style="font-size: 11px; flex: 1">
            select one or more — daemon uses the first one that's reachable
            <span v-if="groupApply.proxies.length" style="color: var(--accent); font-weight: 600">
              · {{ groupApply.proxies.length }} selected
            </span>
          </span>
          <span v-else class="muted" style="font-size: 11px; flex: 1">
            select one or more xray outbounds — daemon uses the first that dials
            <span v-if="groupApply.xrays.length" style="color: var(--accent); font-weight: 600">
              · {{ groupApply.xrays.length }} selected
            </span>
          </span>
        </div>
        <div v-if="groupApply.binding === 'proxy'" class="chip-grid">
          <button v-for="p in proxies" :key="p.id"
                  :class="['app-chip', {active: groupApply.proxies.includes(p.name)}]"
                  @click="toggleGroupProxy(p.name)"
                  :title="`${p.protocol}://${p.host}:${p.port}`">
            <span>{{ p.name }}</span>
            <span class="muted" style="font-size: 10px">{{ p.protocol }}</span>
            <span v-if="groupApply.proxies.includes(p.name)" class="chip-rank">{{ groupApply.proxies.indexOf(p.name) + 1 }}</span>
          </button>
          <span v-if="proxies.length === 0" class="muted" style="font-size: 11px; padding: 4px">
            No proxies configured. Add one in the Proxies tab.
          </span>
        </div>
        <div v-if="groupApply.binding === 'xray'" class="chip-grid">
          <button v-for="x in xrays" :key="x.id"
                  :class="['app-chip', {active: groupApply.xrays.includes(x.name), 'not-running': !x.enabled}]"
                  @click="toggleGroupXray(x.name)"
                  :title="x.enabled ? `127.0.0.1:${x.socksPort}` : 'disabled — rule will fail to dial'">
            <span>{{ x.name }}</span>
            <span class="muted" style="font-size: 10px">xray</span>
            <span v-if="groupApply.xrays.includes(x.name)" class="chip-rank">{{ groupApply.xrays.indexOf(x.name) + 1 }}</span>
          </button>
          <span v-if="xrays.length === 0" class="muted" style="font-size: 11px; padding: 4px">
            No xray outbounds configured. Add one in the Xray tab.
          </span>
        </div>
      </div>
    </div>

    <div class="add-form">
      <div class="row" style="gap: 8px">
        <input v-model="draft.pattern" placeholder="Pattern (e.g. *.bad.com or 1.2.3.0/24)" style="flex: 1" @keyup.enter="add" />
        <select v-model="draft.action" style="width: 100px">
          <option value="block">block</option>
          <option value="route">route</option>
        </select>
        <label class="toggle">
          <input type="checkbox" v-model="draft.enabled" />
          <span class="track"></span>
        </label>
        <button class="primary" @click="add" :disabled="!draftIsValid()">Add</button>
      </div>
      <div v-if="draft.action === 'route'" class="col" style="gap: 10px; margin-top: 10px">
        <div class="row" style="gap: 8px; align-items: center">
          <span class="muted" style="font-size: 11px; min-width: 60px">via:</span>
          <div class="row" style="gap: 0">
            <button :class="['seg', {active: draft.binding === 'iface'}]" @click="draft.binding = 'iface'">Interface</button>
            <button :class="['seg', {active: draft.binding === 'proxy'}]" @click="draft.binding = 'proxy'">Proxy</button>
            <button :class="['seg', {active: draft.binding === 'xray'}]" @click="draft.binding = 'xray'">Xray</button>
          </div>
          <select v-if="draft.binding === 'iface'" v-model="draft.iface" style="flex: 1">
            <option value="">— pick interface —</option>
            <option v-for="i in interfaces" :key="i.name" :value="i.name">{{ ifaceLabel(i) }} (mtu {{ i.mtu }})</option>
          </select>
          <span v-else-if="draft.binding === 'proxy'" class="muted" style="font-size: 11px; flex: 1">
            select one or more — daemon uses the first one that's reachable
            <span v-if="draft.proxies.length" style="color: var(--accent); font-weight: 600">
              · {{ draft.proxies.length }} selected
            </span>
          </span>
          <span v-else class="muted" style="font-size: 11px; flex: 1">
            select one or more xray outbounds — daemon uses the first that dials
            <span v-if="draft.xrays.length" style="color: var(--accent); font-weight: 600">
              · {{ draft.xrays.length }} selected
            </span>
          </span>
        </div>
        <div v-if="draft.binding === 'proxy'" class="chip-grid">
          <button v-for="p in proxies" :key="p.id"
                  :class="['app-chip', {active: draft.proxies.includes(p.name)}]"
                  @click="toggleDraftProxy(p.name)"
                  :title="`${p.protocol}://${p.host}:${p.port}`">
            <span>{{ p.name }}</span>
            <span class="muted" style="font-size: 10px">{{ p.protocol }}</span>
            <span v-if="draft.proxies.includes(p.name)" class="chip-rank">{{ draft.proxies.indexOf(p.name) + 1 }}</span>
          </button>
          <span v-if="proxies.length === 0" class="muted" style="font-size: 11px; padding: 4px">
            No proxies configured. Add one in the Proxies tab.
          </span>
        </div>
        <div v-if="draft.binding === 'xray'" class="chip-grid">
          <button v-for="x in xrays" :key="x.id"
                  :class="['app-chip', {active: draft.xrays.includes(x.name), 'not-running': !x.enabled}]"
                  @click="toggleDraftXray(x.name)"
                  :title="x.enabled ? `127.0.0.1:${x.socksPort}` : 'disabled — rule will fail to dial'">
            <span>{{ x.name }}</span>
            <span class="muted" style="font-size: 10px">xray</span>
            <span v-if="draft.xrays.includes(x.name)" class="chip-rank">{{ draft.xrays.indexOf(x.name) + 1 }}</span>
          </button>
          <span v-if="xrays.length === 0" class="muted" style="font-size: 11px; padding: 4px">
            No xray outbounds configured. Add one in the Xray tab.
          </span>
        </div>
      </div>
    </div>

    <!-- Sticky bulk-action toolbar. Visible only when one or more rules
         are selected. The first row is always a compact summary; the
         expanded editor (with the action picker and segmented
         interface/app/proxy/xray controls) is mounted on demand. -->
    <div v-if="selectedCount > 0" class="bulk-toolbar">
      <div class="row" style="gap: 10px; align-items: center; flex-wrap: wrap">
        <strong>{{ selectedCount }} selected</strong>
        <button v-if="!bulk" class="primary" @click="openBulk">Change to…</button>
        <button @click="selectAllVisible"
                :disabled="selectedCount === filteredRules.length"
                title="Add every rule matching the current search to the selection">
          Select all visible ({{ filteredRules.length }})
        </button>
        <button @click="clearSelection">Clear</button>
      </div>
      <div v-if="bulk" class="col" style="gap: 10px; margin-top: 10px">
        <div class="row" style="gap: 8px; align-items: center">
          <span class="muted" style="font-size: 11px; min-width: 60px">action:</span>
          <select v-model="bulk.action" style="width: 100px">
            <option value="block">block</option>
            <option value="route">route</option>
          </select>
          <button class="primary" @click="applyBulk" :disabled="!bulkIsValid()">
            Apply to {{ selectedCount }} rule{{ selectedCount === 1 ? '' : 's' }}
          </button>
          <button @click="closeBulk">Cancel</button>
        </div>
        <div v-if="bulk.action === 'route'" class="col" style="gap: 10px">
          <div class="row" style="gap: 8px; align-items: center">
            <span class="muted" style="font-size: 11px; min-width: 60px">via:</span>
            <div class="row" style="gap: 0">
              <button :class="['seg', {active: bulk.binding === 'iface'}]" @click="bulk.binding = 'iface'">Interface</button>
              <button :class="['seg', {active: bulk.binding === 'proxy'}]" @click="bulk.binding = 'proxy'">Proxy</button>
              <button :class="['seg', {active: bulk.binding === 'xray'}]" @click="bulk.binding = 'xray'">Xray</button>
            </div>
            <select v-if="bulk.binding === 'iface'" v-model="bulk.iface" style="flex: 1">
              <option value="">— pick interface —</option>
              <option v-for="i in interfaces" :key="i.name" :value="i.name">{{ ifaceLabel(i) }} (mtu {{ i.mtu }})</option>
            </select>
            <span v-else-if="bulk.binding === 'proxy'" class="muted" style="font-size: 11px; flex: 1">
              select one or more — daemon uses the first one that's reachable
              <span v-if="bulk.proxies.length" style="color: var(--accent); font-weight: 600">
                · {{ bulk.proxies.length }} selected
              </span>
            </span>
            <span v-else class="muted" style="font-size: 11px; flex: 1">
              select one or more xray outbounds — daemon uses the first that dials
              <span v-if="bulk.xrays.length" style="color: var(--accent); font-weight: 600">
                · {{ bulk.xrays.length }} selected
              </span>
            </span>
          </div>
          <div v-if="bulk.binding === 'proxy'" class="chip-grid">
            <button v-for="p in proxies" :key="p.id"
                    :class="['app-chip', {active: bulk.proxies.includes(p.name)}]"
                    @click="toggleBulkProxy(p.name)"
                    :title="`${p.protocol}://${p.host}:${p.port}`">
              <span>{{ p.name }}</span>
              <span class="muted" style="font-size: 10px">{{ p.protocol }}</span>
              <span v-if="bulk.proxies.includes(p.name)" class="chip-rank">{{ bulk.proxies.indexOf(p.name) + 1 }}</span>
            </button>
            <span v-if="proxies.length === 0" class="muted" style="font-size: 11px; padding: 4px">
              No proxies configured. Add one in the Proxies tab.
            </span>
          </div>
          <div v-if="bulk.binding === 'xray'" class="chip-grid">
            <button v-for="x in xrays" :key="x.id"
                    :class="['app-chip', {active: bulk.xrays.includes(x.name), 'not-running': !x.enabled}]"
                    @click="toggleBulkXray(x.name)"
                    :title="x.enabled ? `127.0.0.1:${x.socksPort}` : 'disabled — rule will fail to dial'">
              <span>{{ x.name }}</span>
              <span class="muted" style="font-size: 10px">xray</span>
              <span v-if="bulk.xrays.includes(x.name)" class="chip-rank">{{ bulk.xrays.indexOf(x.name) + 1 }}</span>
            </button>
            <span v-if="xrays.length === 0" class="muted" style="font-size: 11px; padding: 4px">
              No xray outbounds configured. Add one in the Xray tab.
            </span>
          </div>
        </div>
      </div>
    </div>

    <!-- Per-section rendering. Each known group gets its own table with
         a header row carrying the bulk actions. Ungrouped (and rules
         the user hand-edited away from a group) lands in the final
         section. Empty sections are skipped so the page stays compact
         under search. -->
    <div v-if="!sections.length && rules.length" class="muted"
         style="text-align: center; padding: 24px">
      No rules match "<code>{{ search }}</code>".
    </div>
    <div v-if="!rules.length" class="muted"
         style="text-align: center; padding: 24px">
      No rules yet. Use the Quick add bar above for one-click groups, or
      the Add form for a single domain. Unmatched queries are allowed by
      default.
    </div>

    <div v-for="sec in sections" :key="sec.group?.key || '__ungrouped__'"
         class="rule-section">
      <!-- Section header -->
      <div class="section-header">
        <!-- Tri-state section checkbox: ticks every rule in this
             section when none/some are selected; clears the section
             when all are already selected. Uses the indeterminate DOM
             property for the "some" state. -->
        <input type="checkbox"
               class="section-check"
               :checked="sectionSelectionState(sec.rules) === 'all'"
               :indeterminate.prop="sectionSelectionState(sec.rules) === 'some'"
               @change="toggleSection(sec.rules)"
               :title="sectionSelectionState(sec.rules) === 'all' ? 'Deselect all rules in this section' : 'Select every rule in this section'" />
        <button class="caret-btn" @click="toggleCollapse(sec.group)"
                :title="isCollapsed(sec.group) ? 'Expand' : 'Collapse'">
          {{ isCollapsed(sec.group) ? '▸' : '▾' }}
        </button>
        <div class="row" style="gap: 8px; align-items: center; flex: 1; cursor: pointer"
             @click="toggleCollapse(sec.group)">
          <GroupIcon v-if="sec.group" :group-key="sec.group.key" :size="20" />
          <strong v-if="sec.group">{{ sec.group.displayName }}</strong>
          <strong v-else style="color: var(--text-dim)">Ungrouped</strong>
          <span class="muted" style="font-size: 11px">
            {{ sec.rules.length }} {{ sec.rules.length === 1 ? 'rule' : 'rules' }}
          </span>
          <!-- State pill: read-only summary, click goes to collapse -->
          <span v-if="sec.group" class="state-pill" :class="'state-' + groupEnabledState(sec.rules)">
            {{ groupEnabledState(sec.rules) === 'on' ? 'all on'
              : groupEnabledState(sec.rules) === 'off' ? 'all off' : 'mixed' }}
          </span>
        </div>
        <!-- Bulk actions: groups only. Ungrouped section is just a label. -->
        <div v-if="sec.group" class="row" style="gap: 6px; align-items: center">
          <button class="bulk-btn"
                  :disabled="groupEnabledState(sec.rules) === 'on'"
                  @click="setGroupEnabledAll(sec.group, true)"
                  title="Turn every rule in this group on">
            Enable all
          </button>
          <button class="bulk-btn"
                  :disabled="groupEnabledState(sec.rules) === 'off'"
                  @click="setGroupEnabledAll(sec.group, false)"
                  title="Turn every rule in this group off">
            Disable all
          </button>
          <button :class="pendingDeleteGroup === sec.group.key ? 'danger primary' : 'danger'"
                  @click="askDeleteGroup(sec.group)">
            {{ pendingDeleteGroup === sec.group.key ? 'Confirm delete?' : 'Delete all' }}
          </button>
        </div>
      </div>

      <!-- Section body: same row template as before, just in its own table.
           Collapsed sections hide the table entirely so the user can
           scan the page by group headers alone. -->
      <table v-if="!isCollapsed(sec.group)" class="section-table">
        <thead>
          <tr>
            <th style="width: 28px"></th>
            <th>Pattern</th>
            <th>Action</th>
            <th>Interface</th>
            <th>Enabled</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <template v-for="r in sec.rules" :key="r.id">
            <tr v-if="editing?.id !== r.id"
                :class="{'rule-iface-down': r.action === 'route' && bindingDown(r.interface), 'rule-selected': isSelected(r.id)}">
              <td style="text-align: center">
                <input type="checkbox"
                       :checked="isSelected(r.id)"
                       @change="toggleSelected(r.id)" />
              </td>
              <td><code>{{ r.pattern }}</code></td>
              <td>
                <span :class="['tag', r.action === 'block' ? 'tag-block' : 'tag-route']">
                  {{ r.action }}
                </span>
                <span v-if="r.action === 'route' && bindingDown(r.interface)"
                      class="tag tag-block" style="margin-left: 6px"
                      :title="ruleIsProxy(r.interface) ? 'Proxy missing — referenced proxy no longer exists'
                            : ruleIsXray(r.interface) ? 'No referenced xray entry is enabled — queries return NXDOMAIN'
                            : 'Configured interface is not up — queries return NXDOMAIN until it comes back'">
                  ⚠ {{ ruleIsProxy(r.interface) ? 'proxy missing'
                       : ruleIsXray(r.interface) ? 'xray off'
                       : 'iface down' }}
                </span>
              </td>
              <td>
                <div v-if="r.action === 'route' && ruleIsProxy(r.interface)" class="row" style="gap: 4px; flex-wrap: wrap">
                  <span v-for="(n, i) in ruleProxyKeys(r.interface)" :key="n"
                        class="row" style="gap: 4px; padding: 2px 6px; border: 1px solid var(--border); border-radius: 12px; font-size: 11px"
                        :title="proxyStatusLabel(n)">
                    <span>{{ n }}</span>
                    <span class="muted">{{ proxyStatusBadge(n) }}</span>
                    <span v-if="i < ruleProxyKeys(r.interface).length - 1" class="muted">·</span>
                  </span>
                </div>
                <div v-else-if="r.action === 'route' && ruleIsXray(r.interface)" class="row" style="gap: 4px; flex-wrap: wrap">
                  <span v-for="(n, i) in ruleXrayNames(r.interface)" :key="n"
                        class="row" style="gap: 4px; padding: 2px 6px; border: 1px solid var(--border); border-radius: 12px; font-size: 11px"
                        :title="xrayStatusLabel(n)">
                    <span>xray:{{ n }}</span>
                    <span class="muted">{{ xrayStatusBadge(n) }}</span>
                    <span v-if="i < ruleXrayNames(r.interface).length - 1" class="muted">·</span>
                  </span>
                </div>
                <code v-else-if="r.action === 'route'" style="font-size: 12px">{{ r.interface }}</code>
                <span v-else class="muted">—</span>

                <!-- Exit IP: the public IP this pattern's traffic appears
                     to come from. Fetched automatically after load; the IP
                     is masked until clicked. Hidden for block rules. -->
                <div v-if="r.action !== 'block'" class="exit-ip">
                  <span v-if="exitLoading[r.id]" class="muted">probing exit IP…</span>
                  <template v-else-if="exitInfo[r.id]">
                    <template v-if="exitInfo[r.id].probed">
                      <span v-if="flagEmoji(exitInfo[r.id].country)" class="flag">{{ flagEmoji(exitInfo[r.id].country) }}</span>
                      <code class="exit-ip-val"
                            :title="revealedExitIPs[r.id] ? 'click to mask' : 'click to reveal full IP'"
                            @click="toggleExitReveal(r.id)">
                        {{ revealedExitIPs[r.id] ? exitInfo[r.id].exitIp : maskIP(exitInfo[r.id].exitIp) }}
                      </code>
                      <span v-if="exitInfo[r.id].city" class="muted">· {{ exitInfo[r.id].city }}</span>
                    </template>
                    <span v-else class="muted" :title="exitInfo[r.id].message">— couldn't determine</span>
                    <button class="link-btn" title="Re-probe exit IP" @click="checkExitIP(r)">↻</button>
                  </template>
                  <span v-else class="muted">queued…</span>
                </div>
              </td>
              <td>
                <label class="toggle" @click.prevent="toggle(r)">
                  <input type="checkbox" :checked="r.enabled" />
                  <span class="track"></span>
                </label>
              </td>
              <td style="white-space: nowrap">
                <button @click="beginEdit(r)" style="margin-right: 4px">Edit</button>
                <button
                  :class="pendingDelete === r.id ? 'danger primary' : 'danger'"
                  @click="askDelete(r)"
                >
                  {{ pendingDelete === r.id ? 'Confirm?' : 'Delete' }}
                </button>
              </td>
            </tr>

            <tr v-else class="edit-row">
              <td colspan="6">
                <div class="edit-card">
                  <div class="row" style="gap: 8px">
                    <input v-model="editing!.pattern"
                           placeholder="Pattern (e.g. *.bad.com or 1.2.3.0/24)"
                           style="flex: 1"
                           @keyup.enter="saveEdit"
                           @keyup.esc="cancelEdit" />
                    <select v-model="editing!.action" style="width: 100px">
                      <option value="block">block</option>
                      <option value="route">route</option>
                    </select>
                    <label class="toggle">
                      <input type="checkbox" v-model="editing!.enabled" />
                      <span class="track"></span>
                    </label>
                    <button class="primary" @click="saveEdit" :disabled="!editingIsValid()">Save</button>
                    <button @click="cancelEdit">Cancel</button>
                  </div>
                  <div v-if="editing!.action === 'route'" class="col" style="gap: 10px; margin-top: 10px">
                    <div class="row" style="gap: 8px; align-items: center">
                      <span class="muted" style="font-size: 11px; min-width: 60px">via:</span>
                      <div class="row" style="gap: 0">
                        <button :class="['seg', {active: editing!.binding === 'iface'}]" @click="editing!.binding = 'iface'">Interface</button>
                        <button :class="['seg', {active: editing!.binding === 'proxy'}]" @click="editing!.binding = 'proxy'">Proxy</button>
                        <button :class="['seg', {active: editing!.binding === 'xray'}]" @click="editing!.binding = 'xray'">Xray</button>
                      </div>
                      <select v-if="editing!.binding === 'iface'" v-model="editing!.iface" style="flex: 1">
                        <option value="">— pick interface —</option>
                        <option v-for="i in interfaces" :key="i.name" :value="i.name">{{ ifaceLabel(i) }} (mtu {{ i.mtu }})</option>
                        <option v-if="editing!.iface && !interfaces.some(i => i.name === editing!.iface)"
                                :value="editing!.iface" disabled>{{ editing!.iface }} — down (saved)</option>
                      </select>
                      <span v-else-if="editing!.binding === 'proxy'" class="muted" style="font-size: 11px; flex: 1">
                        select one or more — daemon uses the first one that's reachable
                        <span v-if="editing!.proxies.length" style="color: var(--accent); font-weight: 600">
                          · {{ editing!.proxies.length }} selected
                        </span>
                      </span>
                      <span v-else class="muted" style="font-size: 11px; flex: 1">
                        select one or more xray outbounds — daemon uses the first that dials
                        <span v-if="editing!.xrays.length" style="color: var(--accent); font-weight: 600">
                          · {{ editing!.xrays.length }} selected
                        </span>
                      </span>
                    </div>
                    <div v-if="editing!.binding === 'proxy'" class="chip-grid">
                      <button v-for="p in proxies" :key="p.id"
                              :class="['app-chip', {active: editing!.proxies.includes(p.name)}]"
                              @click="toggleEditingProxy(p.name)"
                              :title="`${p.protocol}://${p.host}:${p.port}`">
                        <span>{{ p.name }}</span>
                        <span class="muted" style="font-size: 10px">{{ p.protocol }}</span>
                        <span v-if="editing!.proxies.includes(p.name)" class="chip-rank">{{ editing!.proxies.indexOf(p.name) + 1 }}</span>
                      </button>
                      <span v-if="proxies.length === 0" class="muted" style="font-size: 11px; padding: 4px">
                        No proxies configured. Add one in the Proxies tab.
                      </span>
                    </div>
                    <div v-if="editing!.binding === 'xray'" class="chip-grid">
                      <button v-for="x in xrays" :key="x.id"
                              :class="['app-chip', {active: editing!.xrays.includes(x.name), 'not-running': !x.enabled}]"
                              @click="toggleEditingXray(x.name)"
                              :title="x.enabled ? `127.0.0.1:${x.socksPort}` : 'disabled'">
                        <span>{{ x.name }}</span>
                        <span class="muted" style="font-size: 10px">xray</span>
                        <span v-if="editing!.xrays.includes(x.name)" class="chip-rank">{{ editing!.xrays.indexOf(x.name) + 1 }}</span>
                      </button>
                      <span v-if="xrays.length === 0" class="muted" style="font-size: 11px; padding: 4px">
                        No xray outbounds configured. Add one in the Xray tab.
                      </span>
                    </div>
                  </div>
                </div>
              </td>
            </tr>
          </template>
        </tbody>
      </table>
    </div>
  </div>
</template>

<style scoped>
.exit-ip {
  display: flex;
  align-items: center;
  gap: 5px;
  margin-top: 4px;
  font-size: 11px;
}
.exit-ip .flag { font-size: 13px; line-height: 1; }
.exit-ip-val { cursor: pointer; }
.exit-ip-val:hover { text-decoration: underline; }
.link-btn {
  border: none;
  background: transparent;
  padding: 0;
  cursor: pointer;
  color: var(--accent);
  font-size: 11px;
}
.link-btn:hover { text-decoration: underline; }

tr.rule-iface-down td { background: rgba(255, 111, 111, 0.05); }
tr.rule-iface-down code { opacity: 0.85; }
tr.rule-selected td { background: rgba(110, 168, 255, 0.08); }
tr.rule-selected.rule-iface-down td { background: rgba(255, 111, 111, 0.08); }

.bulk-toolbar {
  position: sticky;
  top: 0;
  z-index: 5;
  background: var(--panel);
  border: 1px solid var(--border);
  border-left: 3px solid var(--accent);
  border-radius: 8px;
  padding: 12px 14px;
  margin-bottom: 12px;
}

.section-check {
  margin-right: 4px;
  cursor: pointer;
}

tr.edit-row td {
  padding: 0;
  background: rgba(110, 168, 255, 0.04);
}
.edit-card {
  border-left: 3px solid var(--accent);
  padding: 12px 14px;
}

.add-form {
  background: var(--panel);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 12px;
  margin-bottom: 16px;
}

.seg {
  background: transparent;
  border: 1px solid var(--border);
  border-right: none;
  border-radius: 0;
  padding: 6px 14px;
  color: var(--text-dim);
  font-size: 12px;
}
.seg:first-child { border-top-left-radius: 6px; border-bottom-left-radius: 6px; }
.seg:last-child  { border-right: 1px solid var(--border); border-top-right-radius: 6px; border-bottom-right-radius: 6px; }
.seg.active {
  color: var(--text);
  background: var(--panel-2);
  border-color: var(--accent);
}

.chip-grid {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  max-height: 220px;
  overflow-y: auto;
}

.app-chip {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 4px 10px 4px 6px;
  border: 1px solid var(--border);
  border-radius: 16px;
  background: var(--panel-2);
  cursor: pointer;
  font-size: 12px;
  color: var(--text);
  position: relative;
}
.app-chip:hover { background: var(--border); }
.app-chip.active {
  border-color: var(--accent);
  background: rgba(110, 168, 255, 0.15);
}
.app-chip.not-installed { opacity: 0.45; }
.app-chip.not-running { color: var(--warn); }

.groups-bar {
  background: var(--panel);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 12px;
  margin-bottom: 12px;
}
.group-card {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  padding: 6px 12px 6px 8px;
  border: 1px solid var(--border);
  border-radius: 8px;
  background: var(--panel-2);
  cursor: pointer;
  font-size: 12px;
  color: var(--text);
}
.group-card:hover { background: var(--border); border-color: var(--accent); }
.group-card .group-name { font-weight: 600; }

.chip-rank {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 16px;
  height: 16px;
  border-radius: 50%;
  background: var(--accent);
  color: #fff;
  font-size: 10px;
  font-weight: 700;
  margin-left: 2px;
}

.search-row input[type="search"] {
  padding: 8px 12px;
  background: var(--bg);
  border: 1px solid var(--border);
  border-radius: 6px;
  color: var(--text);
  font-size: 13px;
}
.search-row input[type="search"]:focus {
  outline: none;
  border-color: var(--accent);
}

.rule-section {
  margin-bottom: 18px;
}

.section-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 10px 14px;
  background: var(--panel);
  border: 1px solid var(--border);
  border-bottom: none;
  border-top-left-radius: 8px;
  border-top-right-radius: 8px;
}

.section-table {
  margin-top: 0;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
  border-top: none;
}

.caret-btn {
  background: transparent;
  border: none;
  color: var(--text-dim);
  cursor: pointer;
  font-size: 14px;
  padding: 0 6px 0 0;
  margin: 0;
  line-height: 1;
}
.caret-btn:hover { color: var(--text); }

.state-pill {
  display: inline-flex;
  align-items: center;
  padding: 2px 8px;
  border-radius: 10px;
  font-size: 10px;
  text-transform: uppercase;
  letter-spacing: 0.5px;
  font-weight: 600;
}
.state-pill.state-on    { background: rgba(95, 208, 122, 0.15); color: var(--success); }
.state-pill.state-off   { background: rgba(141, 141, 160, 0.15); color: var(--text-dim); }
.state-pill.state-mixed { background: rgba(255, 200, 110, 0.15); color: var(--warn); }

.bulk-btn {
  padding: 4px 10px;
  font-size: 11px;
  border: 1px solid var(--border);
  background: var(--panel-2);
  color: var(--text);
  border-radius: 4px;
  cursor: pointer;
}
.bulk-btn:hover:not(:disabled) {
  background: var(--border);
  border-color: var(--accent);
}
.bulk-btn:disabled {
  opacity: 0.4;
  cursor: not-allowed;
}
</style>
